version: '3.8'
services:
  klaxoon-client:
    container_name: klaxoon-client
    image: 'node:14.15.1-alpine'
    command: npm run dev
    depends_on:
      - klaxoon-server
    ports:
      - '3003:3000'
    user: node
    volumes:
      - './klaxoon-client:/home/node/app'
    working_dir: /home/node/app

  klaxoon-server:
    container_name: klaxoon-server
    image: 'node:14.15.1-alpine'
    command: npm run dev
    env_file:
      - ./klaxoon-server/.env
    depends_on:
      - mongo-klaxoon
      # - redis-klaxoon
    ports:
      - '3004:3000'
    user: node
    volumes:
      - './klaxoon-server:/home/node/app'
    working_dir: /home/node/app

  mongo-klaxoon:
    container_name: mongo-klaxoon
    image: 'mongo:4.4'
    ports:
      - '27020:27017'
    volumes:
      - 'mongo-data-klaxoon:/data/db'

  # redis-klaxoon:
  #   container_name: redis-klaxoon
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6377:6379

volumes:
  mongo-data-klaxoon: {}
